/**
 * Prompt Composer — composes and decomposes project identity files.
 *
 * The project's base identity (common + per-runtime overrides) is stored as
 * separate markdown files referenced from ProjectPrompts in settings.json.
 * This module composes them into runtime-specific output files (CLAUDE.md,
 * .cursorrules, CODEX.md) with delimiters, and can decompose edits back.
 */

import { existsSync } from "node:fs";
import { join, resolve } from "node:path";
import type { ProjectPrompts } from "../viewer/config";

// ---------------------------------------------------------------------------
// Runtime → output file mapping
// ---------------------------------------------------------------------------

/** Maps runtime identifiers to the file each tool reads at the project root. */
export const RUNTIME_OUTPUT_FILES: Record<string, string> = {
  claude: "CLAUDE.md",
  cursor: ".cursorrules",
  codex: "CODEX.md",
};

// ---------------------------------------------------------------------------
// Delimiters
// ---------------------------------------------------------------------------

const DELIM_OPEN = (section: string) => `<!-- foundry:${section} -->`;
const DELIM_CLOSE = (section: string) => `<!-- /foundry:${section} -->`;

const HEADER = "<!-- Generated by Foundry — edit via .foundry/prompts/ or the viewer -->\n";

// ---------------------------------------------------------------------------
// File ref resolver
// ---------------------------------------------------------------------------

/** Read a file ref (path relative to project root). Returns content or empty string. */
export async function readFileRef(projectPath: string, ref: string): Promise<string> {
  const abs = resolve(projectPath, ref);
  if (!existsSync(abs)) return "";
  return Bun.file(abs).text();
}

/** Write content to a file ref (path relative to project root). Creates dirs as needed. */
export async function writeFileRef(projectPath: string, ref: string, content: string): Promise<void> {
  const abs = resolve(projectPath, ref);
  const dir = abs.substring(0, abs.lastIndexOf("/"));
  if (!existsSync(dir)) {
    const { mkdirSync } = await import("node:fs");
    mkdirSync(dir, { recursive: true });
  }
  await Bun.write(abs, content);
}

// ---------------------------------------------------------------------------
// Compose
// ---------------------------------------------------------------------------

/**
 * Compose a runtime-specific output file from common + override prompt files.
 *
 * @param projectPath - Absolute path to project root
 * @param prompts - ProjectPrompts config (file refs)
 * @param runtime - Runtime identifier (e.g., "claude", "cursor", "codex")
 * @returns Composed content with delimiters, or null if no common file exists
 */
export async function compose(
  projectPath: string,
  prompts: ProjectPrompts,
  runtime: string,
): Promise<string | null> {
  const common = await readFileRef(projectPath, prompts.common);
  if (!common) return null;

  const parts: string[] = [HEADER];

  // Common section
  parts.push(DELIM_OPEN("common"));
  parts.push(common.trim());
  parts.push(DELIM_CLOSE("common"));

  // Runtime-specific override
  const overrideRef = prompts.overrides?.[runtime];
  if (overrideRef) {
    const override = await readFileRef(projectPath, overrideRef);
    if (override.trim()) {
      parts.push("");
      parts.push(DELIM_OPEN(runtime));
      parts.push(override.trim());
      parts.push(DELIM_CLOSE(runtime));
    }
  }

  parts.push(""); // trailing newline
  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Decompose
// ---------------------------------------------------------------------------

export interface DecomposedSections {
  /** Content from the <!-- foundry:common --> section. */
  common: string;
  /** Content from runtime-specific sections, keyed by section name. */
  overrides: Record<string, string>;
}

/**
 * Decompose a composed file back into its sections by parsing delimiters.
 * Returns null if the file doesn't contain Foundry delimiters.
 */
export function decompose(content: string): DecomposedSections | null {
  const sections: Record<string, string> = {};
  const regex = /<!-- foundry:(\w+) -->\n([\s\S]*?)<!-- \/foundry:\1 -->/g;

  let match: RegExpExecArray | null;
  let found = false;

  while ((match = regex.exec(content)) !== null) {
    found = true;
    sections[match[1]] = match[2].trim();
  }

  if (!found) return null;

  const common = sections["common"] ?? "";
  delete sections["common"];

  return { common, overrides: sections };
}

// ---------------------------------------------------------------------------
// Write composed output files
// ---------------------------------------------------------------------------

/**
 * Compose and write output files for all configured runtimes.
 *
 * @param projectPath - Absolute path to project root
 * @param prompts - ProjectPrompts config
 * @param runtimes - Runtime IDs to write for (defaults to all known + any with overrides)
 * @returns Map of runtime → output file path that was written
 */
export async function writeComposed(
  projectPath: string,
  prompts: ProjectPrompts,
  runtimes?: string[],
): Promise<Map<string, string>> {
  // Determine which runtimes to generate for
  const targetRuntimes = runtimes ?? [
    ...Object.keys(RUNTIME_OUTPUT_FILES),
    ...Object.keys(prompts.overrides ?? {}),
  ].filter((v, i, a) => a.indexOf(v) === i); // dedupe

  const written = new Map<string, string>();

  for (const runtime of targetRuntimes) {
    const outputFile = RUNTIME_OUTPUT_FILES[runtime];
    if (!outputFile) continue; // unknown runtime, skip

    const content = await compose(projectPath, prompts, runtime);
    if (!content) continue; // no common file, skip

    const outputPath = join(projectPath, outputFile);
    await Bun.write(outputPath, content);
    written.set(runtime, outputPath);
  }

  return written;
}

// ---------------------------------------------------------------------------
// Decompose edits back to source files
// ---------------------------------------------------------------------------

/**
 * Read a composed output file, decompose it, and write changes back to source files.
 * Only overwrites source files if their content actually changed.
 *
 * @param projectPath - Absolute path to project root
 * @param prompts - ProjectPrompts config (to know where source files live)
 * @param runtime - Which runtime's output file to read
 * @returns true if any source files were updated
 */
export async function decomposeBack(
  projectPath: string,
  prompts: ProjectPrompts,
  runtime: string,
): Promise<boolean> {
  const outputFile = RUNTIME_OUTPUT_FILES[runtime];
  if (!outputFile) return false;

  const outputPath = join(projectPath, outputFile);
  if (!existsSync(outputPath)) return false;

  const content = await Bun.file(outputPath).text();
  const sections = decompose(content);
  if (!sections) return false;

  let updated = false;

  // Write back common if changed
  const currentCommon = await readFileRef(projectPath, prompts.common);
  if (sections.common && sections.common !== currentCommon.trim()) {
    await writeFileRef(projectPath, prompts.common, sections.common + "\n");
    updated = true;
  }

  // Write back overrides if changed
  for (const [section, text] of Object.entries(sections.overrides)) {
    const overrideRef = prompts.overrides?.[section];
    if (!overrideRef) continue;

    const currentOverride = await readFileRef(projectPath, overrideRef);
    if (text !== currentOverride.trim()) {
      await writeFileRef(projectPath, overrideRef, text + "\n");
      updated = true;
    }
  }

  return updated;
}
