import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { mkdirSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import {
  compose,
  decompose,
  writeComposed,
  decomposeBack,
  readFileRef,
  writeFileRef,
  RUNTIME_OUTPUT_FILES,
} from "../src/prompts/composer";
import type { ProjectPrompts } from "../src/viewer/config";

const TMP = join(import.meta.dir, "__tmp_composer__");

beforeEach(() => {
  mkdirSync(join(TMP, ".foundry/prompts"), { recursive: true });
});

afterEach(() => {
  rmSync(TMP, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// readFileRef / writeFileRef
// ---------------------------------------------------------------------------

describe("readFileRef", () => {
  it("returns empty string for missing file", async () => {
    expect(await readFileRef(TMP, ".foundry/prompts/missing.md")).toBe("");
  });

  it("reads existing file content", async () => {
    await Bun.write(join(TMP, ".foundry/prompts/common.md"), "Hello world\n");
    const content = await readFileRef(TMP, ".foundry/prompts/common.md");
    expect(content).toBe("Hello world\n");
  });
});

describe("writeFileRef", () => {
  it("creates dirs and writes file", async () => {
    await writeFileRef(TMP, ".foundry/prompts/deep/nested.md", "nested content\n");
    const content = await Bun.file(join(TMP, ".foundry/prompts/deep/nested.md")).text();
    expect(content).toBe("nested content\n");
  });
});

// ---------------------------------------------------------------------------
// compose
// ---------------------------------------------------------------------------

describe("compose", () => {
  const prompts: ProjectPrompts = {
    common: ".foundry/prompts/common.md",
    overrides: {
      claude: ".foundry/prompts/claude.md",
    },
  };

  it("returns null if common file is missing", async () => {
    expect(await compose(TMP, prompts, "claude")).toBeNull();
  });

  it("composes common-only when no override exists", async () => {
    await Bun.write(join(TMP, ".foundry/prompts/common.md"), "Base identity.\n");
    const result = await compose(TMP, prompts, "cursor");
    expect(result).toContain("<!-- foundry:common -->");
    expect(result).toContain("Base identity.");
    expect(result).toContain("<!-- /foundry:common -->");
    expect(result).not.toContain("<!-- foundry:cursor -->");
  });

  it("composes common + override", async () => {
    await Bun.write(join(TMP, ".foundry/prompts/common.md"), "Base identity.\n");
    await Bun.write(join(TMP, ".foundry/prompts/claude.md"), "Use extended thinking.\n");

    const result = await compose(TMP, prompts, "claude");
    expect(result).toContain("<!-- foundry:common -->");
    expect(result).toContain("Base identity.");
    expect(result).toContain("<!-- /foundry:common -->");
    expect(result).toContain("<!-- foundry:claude -->");
    expect(result).toContain("Use extended thinking.");
    expect(result).toContain("<!-- /foundry:claude -->");
  });

  it("includes generated-by header", async () => {
    await Bun.write(join(TMP, ".foundry/prompts/common.md"), "Base.\n");
    const result = await compose(TMP, prompts, "claude");
    expect(result).toContain("Generated by Foundry");
  });
});

// ---------------------------------------------------------------------------
// decompose
// ---------------------------------------------------------------------------

describe("decompose", () => {
  it("returns null for non-Foundry content", () => {
    expect(decompose("Just some regular markdown.")).toBeNull();
  });

  it("parses common section", () => {
    const content = [
      "<!-- foundry:common -->",
      "Base identity.",
      "<!-- /foundry:common -->",
    ].join("\n");

    const result = decompose(content);
    expect(result).not.toBeNull();
    expect(result!.common).toBe("Base identity.");
    expect(Object.keys(result!.overrides)).toHaveLength(0);
  });

  it("parses common + override sections", () => {
    const content = [
      "<!-- foundry:common -->",
      "Base identity.",
      "<!-- /foundry:common -->",
      "",
      "<!-- foundry:claude -->",
      "Extended thinking.",
      "<!-- /foundry:claude -->",
    ].join("\n");

    const result = decompose(content);
    expect(result!.common).toBe("Base identity.");
    expect(result!.overrides["claude"]).toBe("Extended thinking.");
  });

  it("handles multiple overrides", () => {
    const content = [
      "<!-- foundry:common -->",
      "Base.",
      "<!-- /foundry:common -->",
      "<!-- foundry:claude -->",
      "Claude stuff.",
      "<!-- /foundry:claude -->",
      "<!-- foundry:cursor -->",
      "Cursor stuff.",
      "<!-- /foundry:cursor -->",
    ].join("\n");

    const result = decompose(content);
    expect(result!.overrides["claude"]).toBe("Claude stuff.");
    expect(result!.overrides["cursor"]).toBe("Cursor stuff.");
  });
});

// ---------------------------------------------------------------------------
// writeComposed
// ---------------------------------------------------------------------------

describe("writeComposed", () => {
  it("writes output files for specified runtimes", async () => {
    await Bun.write(join(TMP, ".foundry/prompts/common.md"), "Project X.\n");
    await Bun.write(join(TMP, ".foundry/prompts/claude.md"), "Claude-specific.\n");

    const prompts: ProjectPrompts = {
      common: ".foundry/prompts/common.md",
      overrides: { claude: ".foundry/prompts/claude.md" },
    };

    const written = await writeComposed(TMP, prompts, ["claude"]);
    expect(written.size).toBe(1);
    expect(written.has("claude")).toBe(true);

    const claudeMd = await Bun.file(join(TMP, "CLAUDE.md")).text();
    expect(claudeMd).toContain("Project X.");
    expect(claudeMd).toContain("Claude-specific.");
  });

  it("skips unknown runtimes", async () => {
    await Bun.write(join(TMP, ".foundry/prompts/common.md"), "Base.\n");
    const prompts: ProjectPrompts = { common: ".foundry/prompts/common.md" };
    const written = await writeComposed(TMP, prompts, ["unknown-runtime"]);
    expect(written.size).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// decomposeBack (round-trip)
// ---------------------------------------------------------------------------

describe("decomposeBack", () => {
  it("round-trips compose → decomposeBack", async () => {
    await Bun.write(join(TMP, ".foundry/prompts/common.md"), "Base identity.\n");
    await Bun.write(join(TMP, ".foundry/prompts/claude.md"), "Use extended thinking.\n");

    const prompts: ProjectPrompts = {
      common: ".foundry/prompts/common.md",
      overrides: { claude: ".foundry/prompts/claude.md" },
    };

    // Compose to CLAUDE.md
    await writeComposed(TMP, prompts, ["claude"]);

    // Modify CLAUDE.md directly (simulate user edit)
    const claudePath = join(TMP, "CLAUDE.md");
    let content = await Bun.file(claudePath).text();
    content = content.replace("Base identity.", "Updated base identity.");
    await Bun.write(claudePath, content);

    // Decompose back
    const updated = await decomposeBack(TMP, prompts, "claude");
    expect(updated).toBe(true);

    // Verify source file was updated
    const common = await Bun.file(join(TMP, ".foundry/prompts/common.md")).text();
    expect(common.trim()).toBe("Updated base identity.");
  });

  it("returns false when nothing changed", async () => {
    await Bun.write(join(TMP, ".foundry/prompts/common.md"), "Base.\n");
    const prompts: ProjectPrompts = { common: ".foundry/prompts/common.md" };

    await writeComposed(TMP, prompts, ["claude"]);
    const updated = await decomposeBack(TMP, prompts, "claude");
    expect(updated).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// RUNTIME_OUTPUT_FILES
// ---------------------------------------------------------------------------

describe("RUNTIME_OUTPUT_FILES", () => {
  it("maps known runtimes", () => {
    expect(RUNTIME_OUTPUT_FILES["claude"]).toBe("CLAUDE.md");
    expect(RUNTIME_OUTPUT_FILES["cursor"]).toBe(".cursorrules");
    expect(RUNTIME_OUTPUT_FILES["codex"]).toBe("CODEX.md");
  });
});
